global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'
      continue: true
    - match_re:
        alertname: (APIHighErrorRate|FailedMemoryTransactions|SolanaRPCErrors)
      receiver: 'email-dev-team'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#neuramint-monitoring'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'slack-critical'
    slack_configs:
      - channel: '#neuramint-critical'
        send_resolved: true
        title: '[CRITICAL] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#neuramint-warnings'
        send_resolved: true
        title: '[WARNING] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  - name: 'email-dev-team'
    email_configs:
      - to: 'dev-team@neuramint.com'
        from: 'alertmanager@neuramint.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'alertmanager@neuramint.com'
        auth_password: 'YOUR_SMTP_PASSWORD'
        send_resolved: true
        headers:
          subject: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}' 